CREATE TABLE [dbo].[T_Purchases]
(
	[PurchaseID] INT NOT NULL PRIMARY KEY IDENTITY (1,1),
	[IdUser] INT NOT NULL FOREIGN KEY REFERENCES T_Users(UserID),
	[IdStore] INT NOT NULL FOREIGN KEY REFERENCES T_Store(StoreID),
	[IdProduct] INT NOT NULL FOREIGN KEY REFERENCES T_Products(ProductID)
)
